// Catalog entries for agents.* apply/verify admin surfaces
// (agents.create, agents.join, agents.guidance.takeover, agents.defaults.*,
//  agents.model, agents.heartbeat, agents.policy, agents.constraints,
//  agents.name, agents.description, agents.tools, agents.card.formats,
//  agents.role, agents.skills, agents.delete, agents.hard_delete).

export const AGENTS_APPLY_SURFACES = [
  {
    id: "agents.create",
    stage: "apply",
    risk: "safe",
    method: "POST",
    path: "/watchdog/agents/create",
    operatorPhase: "O2",
    operatorExecutable: true,
    confirmation: "changeset",
    status: "active",
    summary: "创建新 agent，并注入 bootstrap、平台地图与默认 skills。",
  },
  {
    id: "agents.join",
    stage: "apply",
    risk: "safe",
    method: "POST",
    path: "/watchdog/agents/join",
    operatorPhase: "O2",
    confirmation: "changeset",
    status: "active",
    summary: "将本地已有 OpenClaw agent 纳入 watchdog 系统，补齐 binding、平台画像与可接管引导；不会覆盖无管理标记的自定义引导。",
  },
  {
    id: "agents.guidance.takeover",
    stage: "apply",
    risk: "safe",
    method: "POST",
    path: "/watchdog/agents/guidance/takeover",
    operatorPhase: "O2",
    confirmation: "changeset",
    status: "active",
    summary: "显式接管指定 agent 的平台引导文件，可按文件选择；用 watchdog 受管模板覆盖现有自定义引导。",
  },
  {
    id: "agents.defaults.model",
    stage: "apply",
    risk: "safe",
    method: "POST",
    path: "/watchdog/agents/defaults/model",
    operatorPhase: "O2",
    confirmation: "changeset",
    status: "active",
    summary: "修改 agent 默认 primary model。",
  },
  {
    id: "agents.defaults.heartbeat",
    stage: "apply",
    risk: "safe",
    method: "POST",
    path: "/watchdog/agents/defaults/heartbeat",
    operatorPhase: "O2",
    confirmation: "changeset",
    status: "active",
    summary: "修改 agent 默认 heartbeat cadence。",
  },
  {
    id: "agents.defaults.skills",
    stage: "apply",
    risk: "safe",
    method: "POST",
    path: "/watchdog/agents/defaults/skills",
    operatorPhase: "O2",
    confirmation: "changeset",
    status: "active",
    summary: "修改 watchdog 侧配置的 agent 默认 skills。",
  },
  {
    id: "agents.model",
    stage: "apply",
    risk: "safe",
    method: "POST",
    path: "/watchdog/agents/model",
    operatorPhase: "O2",
    confirmation: "changeset",
    status: "active",
    summary: "修改 agent 的 primary model。",
  },
  {
    id: "agents.heartbeat",
    stage: "apply",
    risk: "safe",
    method: "POST",
    path: "/watchdog/agents/heartbeat",
    operatorPhase: "O2",
    confirmation: "changeset",
    status: "active",
    summary: "修改单个 agent 的 heartbeat cadence。",
  },
  {
    id: "agents.policy",
    stage: "apply",
    risk: "safe",
    method: "POST",
    path: "/watchdog/agents/policy",
    operatorPhase: "O2",
    operatorExecutable: true,
    confirmation: "changeset",
    status: "active",
    summary: "修改单个 agent 的实例 policy，例如 gateway、protected、ingressSource 与 specialized。",
  },
  {
    id: "agents.constraints",
    stage: "apply",
    risk: "safe",
    method: "POST",
    path: "/watchdog/agents/constraints",
    operatorPhase: "O2",
    operatorExecutable: true,
    confirmation: "changeset",
    status: "active",
    summary: "修改单个 agent 的 runtime constraints 覆盖值。",
  },
  {
    id: "agents.name",
    stage: "apply",
    risk: "safe",
    method: "POST",
    path: "/watchdog/agents/name",
    operatorPhase: "O2",
    operatorExecutable: true,
    confirmation: "changeset",
    status: "active",
    summary: "修改 agent-card 可见名称。",
  },
  {
    id: "agents.description",
    stage: "apply",
    risk: "safe",
    method: "POST",
    path: "/watchdog/agents/description",
    operatorPhase: "O2",
    operatorExecutable: true,
    confirmation: "changeset",
    status: "active",
    summary: "修改 agent-card 可见描述。",
  },
  {
    id: "agents.tools",
    stage: "apply",
    risk: "safe",
    method: "POST",
    path: "/watchdog/agents/tools",
    operatorPhase: "O2",
    operatorExecutable: true,
    confirmation: "changeset",
    status: "active",
    summary: "修改 agent 的正式 tools 配置，并同步 runtime truth 与 card 投影。",
  },
  {
    id: "agents.card.formats",
    stage: "apply",
    risk: "safe",
    method: "POST",
    path: "/watchdog/agents/card/formats",
    operatorPhase: "O2",
    confirmation: "changeset",
    status: "active",
    summary: "修改 agent-card 的 input/output formats 覆盖值。",
  },
  {
    id: "agents.role",
    stage: "apply",
    risk: "safe",
    method: "POST",
    path: "/watchdog/agents/role",
    operatorPhase: "O2",
    operatorExecutable: true,
    confirmation: "changeset",
    status: "active",
    summary: "修改 agent 的平台 role，并同步 card 默认画像。",
  },
  {
    id: "agents.skills",
    stage: "apply",
    risk: "safe",
    method: "POST",
    path: "/watchdog/agents/skills",
    operatorPhase: "O2",
    operatorExecutable: true,
    confirmation: "changeset",
    status: "active",
    summary: "修改单个 agent 的 configured skills，并同步有效 skills。",
  },
  {
    id: "agents.delete",
    stage: "apply",
    risk: "destructive",
    method: "POST",
    path: "/watchdog/agents/delete",
    operatorPhase: "O2",
    operatorExecutable: true,
    confirmation: "explicit",
    status: "active",
    summary: "删除非保护 agent 配置。属于破坏性结构变更（destructive：apply 前自动拍结构快照兜底）。",
  },
  {
    id: "agents.hard_delete",
    stage: "apply",
    risk: "destructive",
    method: "POST",
    path: "/watchdog/agents/hard-delete",
    operatorPhase: "O2",
    operatorExecutable: true,
    confirmation: "explicit",
    status: "active",
    summary: "删除非保护 agent 配置，或清理未注册的本地 workspace residue，并递归移除目标 workspace 目录（destructive：apply 前自动拍结构快照兜底）。",
  },
];
