// Catalog entries for admin_change_sets.*, schedules.*, automations.*,
// agent_joins.*, graph.*, runtime.loop.*, test_runs.start, test.inject,
// and runtime.reset admin surfaces.

export const APPLY_REST_SURFACES = [
  {
    id: "admin_change_sets.save",
    stage: "apply",
    risk: "safe",
    method: "POST",
    path: "/watchdog/admin-change-sets",
    operatorPhase: "O2",
    confirmation: "changeset",
    status: "active",
    summary: "保存或更新面向 admin surface 的 change-set 草稿对象。",
  },
  {
    id: "admin_change_sets.attach_verification",
    stage: "verify",
    risk: "safe",
    method: "POST",
    path: "/watchdog/admin-change-sets/verification",
    operatorPhase: "O2",
    confirmation: "changeset",
    status: "active",
    summary: "将 test run 或落盘 report 结果绑定到 change-set 草稿，形成验证证据。",
  },
  {
    id: "admin_change_sets.execute",
    stage: "apply",
    risk: "safe",
    method: "POST",
    path: "/watchdog/admin-change-sets/execute",
    operatorPhase: "O2",
    confirmation: "changeset",
    status: "active",
    summary: "按 draft 执行对应 admin surface，并记录 executionHistory。",
  },
  {
    id: "schedules.create",
    stage: "apply",
    risk: "safe",
    method: "POST",
    path: "/watchdog/schedules/create",
    operatorPhase: "O2",
    operatorExecutable: true,
    confirmation: "changeset",
    status: "active",
    summary: "创建 watchdog schedule，并同步 materialize 到原生 OpenClaw cron。",
  },
  {
    id: "schedules.update",
    stage: "apply",
    risk: "safe",
    method: "POST",
    path: "/watchdog/schedules/update",
    operatorPhase: "O2",
    operatorExecutable: true,
    confirmation: "changeset",
    status: "active",
    summary: "更新 watchdog schedule 的 trigger / entry / systemActionDelivery / deliveryTargets，并回写 native cron。",
  },
  {
    id: "schedules.enable",
    stage: "apply",
    risk: "safe",
    method: "POST",
    path: "/watchdog/schedules/enable",
    operatorPhase: "O2",
    operatorExecutable: true,
    confirmation: "changeset",
    status: "active",
    summary: "启用一个已注册的 schedule，并同步启用对应原生 cron job。",
  },
  {
    id: "schedules.disable",
    stage: "apply",
    risk: "safe",
    method: "POST",
    path: "/watchdog/schedules/disable",
    operatorPhase: "O2",
    operatorExecutable: true,
    confirmation: "changeset",
    status: "active",
    summary: "停用一个已注册的 schedule，并同步停用对应原生 cron job。",
  },
  {
    id: "schedules.delete",
    stage: "apply",
    risk: "safe",
    method: "POST",
    path: "/watchdog/schedules/delete",
    operatorPhase: "O2",
    operatorExecutable: true,
    confirmation: "explicit",
    status: "active",
    summary: "删除 watchdog schedule，并移除对应原生 cron job 与 materialization 映射。",
  },
  {
    id: "automations.create",
    stage: "apply",
    risk: "safe",
    method: "POST",
    path: "/watchdog/automations/create",
    operatorPhase: "O2",
    operatorExecutable: true,
    confirmation: "changeset",
    status: "active",
    summary: "创建一个长期 automation 对象，定义 objective、entry、wake policy、governance 和 system_action delivery。",
  },
  {
    id: "automations.update",
    stage: "apply",
    risk: "safe",
    method: "POST",
    path: "/watchdog/automations/update",
    operatorPhase: "O2",
    operatorExecutable: true,
    confirmation: "changeset",
    status: "active",
    summary: "更新 automation 的 objective、entry、wake policy、governance、deliveryTargets 与 adapter 指向。",
  },
  {
    id: "automations.enable",
    stage: "apply",
    risk: "safe",
    method: "POST",
    path: "/watchdog/automations/enable",
    operatorPhase: "O2",
    operatorExecutable: true,
    confirmation: "changeset",
    status: "active",
    summary: "启用一个 automation，并把 runtime state 置为 idle，允许后续 wake engine 接管。",
  },
  {
    id: "automations.disable",
    stage: "apply",
    risk: "safe",
    method: "POST",
    path: "/watchdog/automations/disable",
    operatorPhase: "O2",
    operatorExecutable: true,
    confirmation: "changeset",
    status: "active",
    summary: "停用一个 automation，并把 runtime state 置为 paused。",
  },
  {
    id: "automations.run",
    stage: "apply",
    risk: "safe",
    method: "POST",
    path: "/watchdog/automations/run",
    operatorPhase: "O2",
    operatorExecutable: true,
    confirmation: "none",
    status: "active",
    summary: "立即触发一个 automation round。若当前已有活动 round，则只返回运行态摘要而不会重复启动。",
  },
  {
    id: "automations.governance",
    stage: "apply",
    risk: "safe",
    method: "POST",
    path: "/watchdog/automations/governance",
    operatorPhase: "O2",
    operatorExecutable: true,
    confirmation: "changeset",
    status: "active",
    summary: "ProfileLifecycle 安全阀：disableGovernanceSnapshot 全局熔断（忽略异常收紧 snapshot 回 spec 默认）；reviveProfile 复活 retired profile 并重置派生 streak。",
  },
  {
    id: "automations.delete",
    stage: "apply",
    risk: "destructive",
    method: "POST",
    path: "/watchdog/automations/delete",
    operatorPhase: "later",
    confirmation: "explicit",
    status: "active",
    summary: "删除 automation spec 与 runtime state。属于破坏性结构变更。",
  },
  {
    id: "agent_joins.create",
    stage: "apply",
    risk: "safe",
    method: "POST",
    path: "/watchdog/agent-joins/create",
    operatorPhase: "O2",
    operatorExecutable: true,
    confirmation: "changeset",
    status: "active",
    summary: "创建一个外部 agent join spec，声明平台 alias、protocol、adapter 与基础能力。",
  },
  {
    id: "agent_joins.update",
    stage: "apply",
    risk: "safe",
    method: "POST",
    path: "/watchdog/agent-joins/update",
    operatorPhase: "O2",
    operatorExecutable: true,
    confirmation: "changeset",
    status: "active",
    summary: "更新外部 agent join spec 的协议、角色映射、能力声明与 adapter 信息。",
  },
  {
    id: "agent_joins.enable",
    stage: "apply",
    risk: "safe",
    method: "POST",
    path: "/watchdog/agent-joins/enable",
    operatorPhase: "O2",
    operatorExecutable: true,
    confirmation: "changeset",
    status: "active",
    summary: "启用一个 agent join spec，允许它被视为可用接入对象。",
  },
  {
    id: "agent_joins.disable",
    stage: "apply",
    risk: "safe",
    method: "POST",
    path: "/watchdog/agent-joins/disable",
    operatorPhase: "O2",
    operatorExecutable: true,
    confirmation: "changeset",
    status: "active",
    summary: "停用一个 agent join spec，但保留声明和历史配置。",
  },
  {
    id: "agent_joins.delete",
    stage: "apply",
    risk: "destructive",
    method: "POST",
    path: "/watchdog/agent-joins/delete",
    operatorPhase: "later",
    operatorExecutable: true,
    confirmation: "explicit",
    status: "active",
    summary: "删除一个外部 agent join spec。属于破坏性结构变更。",
  },
  {
    id: "graph.edge.add",
    stage: "apply",
    risk: "safe",
    method: "POST",
    path: "/watchdog/graph/edge/add",
    operatorPhase: "O2",
    operatorExecutable: true,
    confirmation: "changeset",
    status: "active",
    summary: "新增一条显式有向协作边，并刷新 BUILDING-MAP / PLATFORM-GUIDE。",
  },
  {
    id: "graph.edge.delete",
    stage: "apply",
    risk: "safe",
    method: "POST",
    path: "/watchdog/graph/edge/delete",
    operatorPhase: "O2",
    operatorExecutable: true,
    confirmation: "changeset",
    status: "active",
    summary: "删除一条显式有向协作边，并刷新 BUILDING-MAP / PLATFORM-GUIDE。",
  },
  {
    id: "graph.loop.compose",
    stage: "apply",
    risk: "structural",
    method: "POST",
    path: "/watchdog/graph/loop/compose",
    operatorPhase: "O2",
    operatorExecutable: true,
    confirmation: "changeset",
    status: "active",
    summary: "按给定顺序把多个 agent 连接成闭环，并一次性刷新 BUILDING-MAP / PLATFORM-GUIDE。",
  },
  {
    id: "graph.loop.delete",
    stage: "apply",
    risk: "structural",
    method: "POST",
    path: "/watchdog/graph/loop/delete",
    operatorPhase: "O2",
    operatorExecutable: true,
    confirmation: "changeset",
    status: "active",
    summary: "按 loopId 注销一个已注册的 LoopSpec（授权边保留，可经 graph.loop.compose 复原）。",
  },
  {
    id: "skills.create",
    stage: "apply",
    risk: "safe",
    method: "POST",
    path: "/watchdog/skills/create",
    operatorPhase: "O2",
    operatorExecutable: true,
    confirmation: "changeset",
    status: "active",
    summary: "新建一个 skill（写 skills/<id>/SKILL.md，含 name/description frontmatter）。new-only 不覆盖既有 skill；不自动注入给任何 agent（注入走 agents.skills）。",
  },
  {
    id: "graph.loop.repair",
    stage: "apply",
    risk: "structural",
    method: "POST",
    path: "/watchdog/graph/loop/repair",
    operatorPhase: "O2",
    operatorExecutable: true,
    confirmation: "changeset",
    status: "active",
    summary: "按已登记的 LoopSpec 补齐缺失边，修复 broken / missing-edge loop。",
  },
  {
    id: "runtime.loop.start",
    stage: "apply",
    risk: "safe",
    method: "POST",
    path: "/watchdog/runtime/loop/start",
    operatorPhase: "O2",
    operatorExecutable: true,
    confirmation: "none",
    status: "active",
    summary: "把真实任务直接送进一个已登记且 active 的 graph-backed loop，从指定 start agent 起步；未指定时默认使用 entry agent。",
  },
  {
    id: "runtime.loop.interrupt",
    stage: "apply",
    risk: "structural",
    method: "POST",
    path: "/watchdog/runtime/loop/interrupt",
    operatorPhase: "O2",
    operatorExecutable: true,
    confirmation: "changeset",
    status: "active",
    summary: "中断当前 active loop，并把 active loop session 归档为 interrupted。",
  },
  {
    id: "runtime.loop.resume",
    stage: "apply",
    risk: "structural",
    method: "POST",
    path: "/watchdog/runtime/loop/resume",
    operatorPhase: "O2",
    operatorExecutable: true,
    confirmation: "changeset",
    status: "active",
    summary: "从最近一次 loop session 或指定 loopId 恢复 loop runtime，并重新投递目标阶段 contract。",
  },
  {
    id: "test_runs.start",
    stage: "verify",
    risk: "structural",
    method: "POST",
    path: "/watchdog/test-runs/start",
    operatorPhase: "O2",
    operatorExecutable: true,
    confirmation: "changeset",
    status: "active",
    summary: "启动结构化测试运行，用于验证系统改动。operator 可主动触发 verify。",
  },
  {
    id: "test.inject",
    stage: "verify",
    risk: "safe",
    method: "POST",
    path: "/watchdog/tests/inject",
    operatorPhase: "O2",
    operatorExecutable: true,
    confirmation: "changeset",
    status: "active",
    summary: "向统一 ingress 注入测试消息，并可显式指定 route hint / intent / phases。operator 可主动触发 verify。",
  },
  {
    id: "runtime.reset",
    stage: "apply",
    risk: "destructive",
    method: "POST",
    path: "/watchdog/reset",
    operatorPhase: "later",
    confirmation: "explicit",
    status: "active",
    summary: "清空 tracker/queue/state 并放弃活动 contract。默认不应自动执行。",
  },
];
