// Catalog entries for all stage:"inspect" (read-only GET) admin surfaces.

export const INSPECT_SURFACES = [
  {
    id: "operator.snapshot",
    stage: "inspect",
    risk: "read",
    method: "GET",
    path: "/watchdog/operator-snapshot",
    operatorPhase: "O1",
    confirmation: "none",
    status: "active",
    summary: "读取 operator 统一前台快照，聚合 agents、surfaces、change-sets、work items、delivery tickets、tests 与 runtime 摘要。",
  },
  {
    id: "agents.list",
    stage: "inspect",
    risk: "read",
    method: "GET",
    path: "/watchdog/agents",
    operatorPhase: "O1",
    confirmation: "none",
    status: "active",
    summary: "读取 agent 列表、role、skills、capabilities 与约束。",
  },
  {
    id: "agents.discovery",
    stage: "inspect",
    risk: "read",
    method: "GET",
    path: "/watchdog/agents/discovery",
    operatorPhase: "O1",
    confirmation: "none",
    status: "active",
    summary: "检测本地 OpenClaw agent 的纳管状态，区分可立即 join 的对象与保留自定义引导、需人工关注的对象。",
  },
  {
    id: "skills.list",
    stage: "inspect",
    risk: "read",
    method: "GET",
    path: "/watchdog/skills",
    operatorPhase: "O1",
    confirmation: "none",
    status: "active",
    summary: "读取本地 skill 目录、描述、默认启用情况与绑定关系。",
  },
  {
    id: "admin_surfaces.list",
    stage: "inspect",
    risk: "read",
    method: "GET",
    path: "/watchdog/admin-surfaces",
    operatorPhase: "O1",
    confirmation: "none",
    status: "active",
    summary: "读取当前 inspect / apply / verify 管理面地图与模板。",
  },
  {
    id: "admin_change_sets.list",
    stage: "inspect",
    risk: "read",
    method: "GET",
    path: "/watchdog/admin-change-sets",
    operatorPhase: "O1",
    confirmation: "none",
    status: "active",
    summary: "读取已保存的 change-set 草稿列表与摘要。",
  },
  {
    id: "admin_change_sets.detail",
    stage: "inspect",
    risk: "read",
    method: "GET",
    path: "/watchdog/admin-change-sets/detail",
    operatorPhase: "O1",
    confirmation: "none",
    status: "active",
    summary: "读取单个 change-set 草稿的完整结构与验证计划。",
  },
  {
    id: "admin_change_sets.preview",
    stage: "inspect",
    risk: "read",
    method: "GET",
    path: "/watchdog/admin-change-sets/preview",
    operatorPhase: "O2",
    confirmation: "none",
    status: "active",
    summary: "预览一个 change-set draft 是否已具备可执行条件。",
  },
  {
    id: "work_items.list",
    stage: "inspect",
    risk: "read",
    method: "GET",
    path: "/watchdog/work-items",
    operatorPhase: "O1",
    confirmation: "none",
    status: "active",
    summary: "读取当前 lifecycle work item 列表与运行时快照。",
  },
  {
    id: "schedules.list",
    stage: "inspect",
    risk: "read",
    method: "GET",
    path: "/watchdog/schedules",
    operatorPhase: "O1",
    confirmation: "none",
    status: "active",
    summary: "读取 watchdog 侧 schedule registry，包含 cron 触发、入口、system_action delivery 与外部投递目标。",
  },
  {
    id: "automations.list",
    stage: "inspect",
    risk: "read",
    method: "GET",
    path: "/watchdog/automations",
    operatorPhase: "O1",
    confirmation: "none",
    status: "active",
    summary: "读取 automation registry 与 runtime state，查看长期目标、wake policy、governance 与当前 round/best-result 摘要。",
  },
  {
    id: "agent_joins.list",
    stage: "inspect",
    risk: "read",
    method: "GET",
    path: "/watchdog/agent-joins/registry",
    operatorPhase: "O1",
    confirmation: "none",
    status: "active",
    summary: "读取外部 agent join registry，查看协议类型、平台角色映射、adapter 形态与接入 readiness。",
  },
  {
    id: "system_action_delivery_tickets.list",
    stage: "inspect",
    risk: "read",
    method: "GET",
    path: "/watchdog/system-action-delivery-tickets",
    operatorPhase: "O1",
    confirmation: "none",
    status: "active",
    summary: "读取 runtime 持有的 system_action delivery ticket 台账与送达状态。",
  },
  {
    id: "runtime.read",
    stage: "inspect",
    risk: "read",
    method: "GET",
    path: "/watchdog/runtime",
    operatorPhase: "O1",
    confirmation: "none",
    status: "active",
    summary: "读取 tracker、dispatch queue 与 runtime target 状态。",
  },
  {
    id: "models.list",
    stage: "inspect",
    risk: "read",
    method: "GET",
    path: "/watchdog/models",
    operatorPhase: "O1",
    confirmation: "none",
    status: "active",
    summary: "读取当前配置中的模型清单。",
  },
  {
    id: "agents.defaults.read",
    stage: "inspect",
    risk: "read",
    method: "GET",
    path: "/watchdog/agents/defaults",
    operatorPhase: "O1",
    confirmation: "none",
    status: "active",
    summary: "读取 agent 默认 model、heartbeat、skills 与平台注入信息。",
  },
  {
    id: "test_runs.list",
    stage: "inspect",
    risk: "read",
    method: "GET",
    path: "/watchdog/test-runs",
    operatorPhase: "O1",
    confirmation: "none",
    status: "active",
    summary: "读取测试运行列表与摘要。",
  },
  {
    id: "test_runs.detail",
    stage: "inspect",
    risk: "read",
    method: "GET",
    path: "/watchdog/test-runs/detail",
    operatorPhase: "O1",
    confirmation: "none",
    status: "active",
    summary: "读取单次测试运行的详细结果和 contractRuntime 快照。",
  },
];
