// dashboard-charts.js — 图表页（主页/工作流的同级页）。
//
// 从 charts.json（CLI-system inspect.charts，只读）取图，每张渲染成一个绝对定位的可拖拽面板。
// 拖拽落点经 apply.chart_move（POST /watchdog/charts/move）服务端持久化，刷新不丢。
// 图表 spec 由可视化大师（viz-master）产出；本页只读 + 渲染 + 摆放，不生成内容。
// NASA-Punk 平面化，错误经 toast 反馈。

import { esc, getToken, toast } from "./dashboard-common.js";
import { initDashboardSubpage } from "./dashboard-subpage-init.js";
import { getCurrentLang } from "./dashboard-i18n.js";
import { renderChartSvg } from "./dashboard-chart-render.js";
import { makeDraggable } from "./dashboard-draggable-widget.js";

function L(zh, en) {
  return getCurrentLang() === "zh-CN" ? zh : en;
}

function buildApiUrl(path) {
  const token = getToken();
  if (!token) return path;
  return `${path}${path.includes("?") ? "&" : "?"}token=${encodeURIComponent(token)}`;
}

async function fetchJson(path) {
  const res = await fetch(buildApiUrl(path), { headers: { "Content-Type": "application/json" } });
  const text = await res.text();
  let data = null;
  try { data = text ? JSON.parse(text) : null; } catch { data = null; }
  if (!res.ok) throw new Error(data?.error || `HTTP ${res.status}`);
  return data;
}

async function postAction(path, payload) {
  const res = await fetch(buildApiUrl(path), {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(payload || {}),
  });
  const text = await res.text();
  let data = null;
  try { data = text ? JSON.parse(text) : null; } catch { data = null; }
  if (!res.ok || (data && data.ok === false)) throw new Error(data?.error || `HTTP ${res.status}`);
  return data;
}

// inspect.charts returns the registry list; tolerate both a bare array and a { charts: [...] } envelope.
function readCharts(data) {
  if (Array.isArray(data)) return data;
  if (Array.isArray(data?.charts)) return data.charts;
  return [];
}

// Build one draggable chart panel from a registry entry { id, label, spec, position }.
function buildPanel(chart) {
  const panel = document.createElement("div");
  panel.className = "chart-panel";
  panel.dataset.chartId = chart.id;
  const x = Number.isFinite(chart.position?.x) ? chart.position.x : 0;
  const y = Number.isFinite(chart.position?.y) ? chart.position.y : 0;
  panel.style.left = `${x}px`;
  panel.style.top = `${y}px`;
  panel.innerHTML = `
    <div class="chart-panel__header">
      <span class="chart-panel__title">${esc(chart.label || chart.id)}</span>
      <button class="chart-panel__regen" type="button" title="${esc(L("重新载入", "Reload"))}">↻</button>
    </div>
    <div class="chart-panel__body">${renderChartSvg(chart.spec || {})}</div>
  `;

  // Drag → persist position server-side via apply.chart_move (charts are platform state, not localStorage).
  makeDraggable(panel, {
    onCommit: async ({ x: nx, y: ny }) => {
      try {
        await postAction("/watchdog/charts/move", { chartId: chart.id, x: nx, y: ny });
      } catch (err) {
        toast(`${L("位置保存失败", "Save position failed")}: ${err.message}`, "error");
      }
    },
  });

  // Regen = reload this chart's spec from the store. "Ask the visualization master to
  // regenerate with new parameters" arrives with the viz-master delegation stage.
  panel.querySelector(".chart-panel__regen").addEventListener("click", (e) => {
    e.stopPropagation();
    loadCharts();
  });

  return panel;
}

async function loadCharts() {
  const host = document.getElementById("chartsCanvas");
  if (!host) return;
  try {
    const data = await fetchJson("/watchdog/inspect?surface=inspect.charts");
    const charts = readCharts(data);
    host.innerHTML = "";
    if (!charts.length) {
      host.innerHTML = `<div class="charts-empty">${esc(L("暂无图表 — 由可视化大师生成", "No charts yet — generated by the visualization master"))}</div>`;
      return;
    }
    for (const chart of charts) host.appendChild(buildPanel(chart));
  } catch (err) {
    toast(`${L("加载失败", "Load failed")}: ${err.message}`, "error");
  }
}

function init() {
  try {
    initDashboardSubpage({ page: "charts" });
    loadCharts();
  } catch (err) {
    console.error("[charts] init failed", err);
  }
}

init();
