// Input-field definitions for agents.* admin surfaces.
// agent_joins.* fields live in ./agent-joins.js

export const AGENT_INPUT_FIELDS = Object.freeze({
  "agents.create": [
    {
      key: "id",
      label: "AGENT ID",
      type: "text",
      required: true,
      aliases: ["agentId"],
      placeholder: "new-agent-id",
      description: "OpenClaw config id and workspace suffix.",
    },
    {
      key: "role",
      label: "ROLE",
      type: "select",
      required: true,
      optionsSource: "roles",
      defaultValue: "agent",
      description: "Bootstrap role profile used to inject base card + defaults.",
    },
    {
      key: "model",
      label: "MODEL",
      type: "combo",
      optionsSource: "models",
      placeholder: "leave blank to inherit agent default model",
      description: "Optional override for the new agent primary model.",
    },
  ],
  "agents.join": [
    {
      key: "agentId",
      label: "AGENT",
      type: "text",
      required: true,
      placeholder: "existing-agent-id",
      description: "Configured agent id, or the discovered workspace candidate id you want to enroll.",
    },
    {
      key: "workspacePath",
      label: "WORKSPACE",
      type: "text",
      placeholder: "Required only for local-workspace candidates",
      description: "Absolute or ~/ path for a discovered local workspace candidate that is not yet in openclaw.json.",
    },
    {
      key: "role",
      label: "ROLE",
      type: "select",
      optionsSource: "roles",
      description: "Optional explicit role override used when the local candidate is enrolled.",
    },
  ],
  "agents.guidance.takeover": [
    {
      key: "agentId",
      label: "AGENT",
      type: "select",
      required: true,
      optionsSource: "agents",
      description: "Configured agent whose custom guidance docs should be replaced by watchdog-managed guidance.",
    },
    {
      key: "files",
      label: "FILES",
      type: "checkbox_group",
      options: [
        { value: "SOUL.md", label: "SOUL.md", detail: "Role identity and execution contract." },
        { value: "HEARTBEAT.md", label: "HEARTBEAT.md", detail: "Heartbeat wake-up contract." },
        { value: "AGENTS.md", label: "AGENTS.md", detail: "Operator rule + collaboration protocol." },
        { value: "BUILDING-MAP.md", label: "BUILDING-MAP.md", detail: "Building directory only." },
        { value: "COLLABORATION-GRAPH.md", label: "COLLABORATION-GRAPH.md", detail: "Fixed-pipeline topology (not collaboration authorization)." },
        { value: "DELIVERY.md", label: "DELIVERY.md", detail: "Terminal + system_action delivery semantics." },
        { value: "PLATFORM-GUIDE.md", label: "PLATFORM-GUIDE.md", detail: "Execution guidance + outbox contract." },
      ],
      description: "Optional subset. Runtime will enforce the canonical role-specific guidance set for the selected agent.",
    },
  ],
  "agents.defaults.model": [
    {
      key: "model",
      label: "DEFAULT MODEL",
      type: "combo",
      required: true,
      optionsSource: "models",
      description: "Primary model inherited by new agents unless they override it.",
    },
  ],
  "agents.defaults.heartbeat": [
    {
      key: "every",
      label: "DEFAULT HEARTBEAT",
      type: "text",
      required: true,
      placeholder: "30m",
      description: "Duration like 30m, 12h, 1d.",
    },
  ],
  "agents.defaults.skills": [
    {
      key: "skills",
      canonicalPath: "skills",
      label: "DEFAULT SKILLS",
      type: "checkbox_group",
      optionsSource: "skills",
      aliases: ["skillsText"],
      description: "Configured default skills. Runtime-forced platform injections are added separately.",
    },
  ],
  "agents.model": [
    {
      key: "agentId",
      label: "AGENT",
      type: "select",
      required: true,
      optionsSource: "agents",
      description: "Target agent whose primary model will be updated.",
    },
    {
      key: "model",
      label: "MODEL",
      type: "combo",
      required: true,
      optionsSource: "models",
      description: "New primary model for the selected agent.",
    },
  ],
  "agents.heartbeat": [
    {
      key: "agentId",
      label: "AGENT",
      type: "select",
      required: true,
      optionsSource: "agents",
      description: "Target agent whose heartbeat cadence will be changed.",
    },
    {
      key: "every",
      label: "HEARTBEAT",
      type: "text",
      required: true,
      placeholder: "30m / 12h / default",
      description: "Duration like 30m or use default to inherit platform default cadence.",
    },
  ],
  "agents.policy": [
    {
      key: "agentId",
      label: "AGENT",
      type: "select",
      required: true,
      optionsSource: "agents",
      description: "Target agent whose instance policy will be changed.",
    },
    {
      key: "gateway",
      label: "GATEWAY",
      type: "select",
      options: [
        { value: "", label: "KEEP CURRENT" },
        { value: "default", label: "RESET TO DEFAULT" },
        { value: "true", label: "FORCE TRUE" },
        { value: "false", label: "FORCE FALSE" },
      ],
      valueType: "boolean_token",
      description: "Whether this agent is treated as an ingress / delivery gateway.",
    },
    {
      key: "protected",
      label: "PROTECTED",
      type: "select",
      options: [
        { value: "", label: "KEEP CURRENT" },
        { value: "default", label: "RESET TO DEFAULT" },
        { value: "true", label: "FORCE TRUE" },
        { value: "false", label: "FORCE FALSE" },
      ],
      valueType: "boolean_token",
      description: "Protected agents cannot be deleted by runtime admin surfaces.",
    },
    {
      key: "ingressSource",
      label: "INGRESS SOURCE",
      type: "text",
      placeholder: "blank=keep current, default=reset, webui / qq / test",
      description: "Optional ingress source label consumed by gateway reply routing.",
    },
    {
      key: "specialized",
      label: "SPECIALIZED",
      type: "select",
      options: [
        { value: "", label: "KEEP CURRENT" },
        { value: "default", label: "RESET TO DEFAULT" },
        { value: "true", label: "FORCE TRUE" },
        { value: "false", label: "FORCE FALSE" },
      ],
      valueType: "boolean_token",
      description: "Executor-only policy used to mark a worker as specialized.",
    },
  ],
  "agents.skills": [
    {
      key: "agentId",
      label: "AGENT",
      type: "select",
      required: true,
      optionsSource: "agents",
      description: "Target agent whose configured skills will be updated.",
    },
    {
      key: "skills",
      canonicalPath: "skills",
      label: "CONFIGURED SKILLS",
      type: "checkbox_group",
      optionsSource: "skills",
      aliases: ["skillsText"],
      description: "Platform defaults remain injected separately; this edits configured extras only.",
    },
  ],
  "agents.constraints": [
    {
      key: "agentId",
      label: "AGENT",
      type: "select",
      required: true,
      optionsSource: "agents",
      description: "Target agent whose runtime constraint overrides will be changed.",
    },
    {
      key: "serialExecution",
      label: "SERIAL EXECUTION",
      type: "select",
      options: [
        { value: "", label: "KEEP CURRENT" },
        { value: "default", label: "RESET TO DEFAULT" },
        { value: "true", label: "FORCE TRUE" },
        { value: "false", label: "FORCE FALSE" },
      ],
      valueType: "boolean_token",
      fallbackPaths: ["constraints.serialExecution"],
      description: "Blank keeps current value. Use default to remove the override.",
    },
    {
      key: "maxConcurrent",
      label: "MAX CONCURRENT",
      type: "text",
      inputMode: "numeric",
      placeholder: "blank=keep current, default=reset",
      fallbackPaths: ["constraints.maxConcurrent"],
      description: "Integer >= 1 or default.",
    },
    {
      key: "timeoutSeconds",
      label: "TIMEOUT SECONDS",
      type: "text",
      inputMode: "numeric",
      placeholder: "blank=keep current, default=reset",
      fallbackPaths: ["constraints.timeoutSeconds"],
      description: "Integer >= 1 or default.",
    },
    {
      key: "maxRetry",
      label: "MAX RETRY",
      type: "text",
      inputMode: "numeric",
      placeholder: "blank=keep current, default=reset",
      fallbackPaths: ["constraints.maxRetry"],
      description: "Integer >= 0 or default.",
    },
  ],
  "agents.name": [
    {
      key: "agentId",
      label: "AGENT",
      type: "select",
      required: true,
      optionsSource: "agents",
      description: "Target agent whose visible card name will be updated.",
    },
    {
      key: "name",
      label: "VISIBLE NAME",
      type: "text",
      required: true,
      placeholder: "Human-readable card name",
      description: "Shown in the platform-facing agent card.",
    },
  ],
  "agents.description": [
    {
      key: "agentId",
      label: "AGENT",
      type: "select",
      required: true,
      optionsSource: "agents",
      description: "Target agent whose visible description will be updated.",
    },
    {
      key: "description",
      label: "DESCRIPTION",
      type: "textarea",
      required: true,
      placeholder: "Short role description for the card",
      description: "Visible platform description stored in agent-card.json.",
    },
  ],
  "agents.tools": [
    {
      key: "agentId",
      label: "AGENT",
      type: "select",
      required: true,
      optionsSource: "agents",
      description: "Target agent whose runtime tools truth will be updated.",
    },
    {
      key: "toolsText",
      canonicalPath: "tools",
      label: "TOOLS",
      type: "textarea",
      valueType: "string_list",
      required: true,
      fallbackPaths: ["tools"],
      placeholder: "read\nwrite\nedit",
      description: "Comma/newline separated tools. Use default to clear the configured override.",
    },
  ],
  "agents.card.formats": [
    {
      key: "agentId",
      label: "AGENT",
      type: "select",
      required: true,
      optionsSource: "agents",
      description: "Target agent whose input/output formats will be updated.",
    },
    {
      key: "inputFormatsText",
      canonicalPath: "inputFormats",
      label: "INPUT FORMATS",
      type: "textarea",
      valueType: "string_list",
      required: true,
      fallbackPaths: ["inputFormats"],
      placeholder: "contract-json\ndirect-request",
      description: "Comma/newline separated input formats. Use default to clear the override.",
    },
    {
      key: "outputFormatsText",
      canonicalPath: "outputFormats",
      label: "OUTPUT FORMATS",
      type: "textarea",
      valueType: "string_list",
      required: true,
      fallbackPaths: ["outputFormats"],
      placeholder: "result-md",
      description: "Comma/newline separated output formats. Use default to clear the override.",
    },
  ],
  "agents.role": [
    {
      key: "agentId",
      label: "AGENT",
      type: "select",
      required: true,
      optionsSource: "agents",
      description: "Target agent whose platform role will be changed.",
    },
    {
      key: "role",
      label: "ROLE",
      type: "select",
      required: true,
      optionsSource: "roles",
      description: "Role change also resyncs the default card profile for that agent.",
    },
  ],
  "agents.delete": [
    {
      key: "agentId",
      label: "AGENT",
      type: "select",
      required: true,
      optionsSource: "agents",
      description: "Deletes a non-protected agent definition. Protected agents will still be rejected by runtime.",
    },
  ],
  "agents.hard_delete": [
    {
      key: "agentId",
      label: "AGENT",
      type: "text",
      required: true,
      placeholder: "configured-agent-id or local-workspace residue id",
      description: "Deletes a non-protected agent definition or a discovered local workspace residue, then removes the resolved workspace directory.",
    },
  ],
});
