// Input-field definitions for agent_joins.* admin surfaces.

export const AGENT_JOINS_INPUT_FIELDS = Object.freeze({
  "agent_joins.create": [
    {
      key: "id",
      label: "JOIN ID",
      type: "text",
      required: true,
      aliases: ["joinId"],
      placeholder: "external-lab-main",
      description: "Stable id for this external agent join spec.",
    },
    {
      key: "localAgentId",
      label: "LOCAL ALIAS",
      type: "text",
      required: true,
      placeholder: "external-agent-main",
      description: "Platform-facing alias used to represent this external agent inside OpenClaw.",
    },
    {
      key: "platformRole",
      label: "PLATFORM ROLE",
      type: "select",
      required: true,
      optionsSource: "roles",
      defaultValue: "agent",
      description: "Role that this external agent should be treated as inside the platform.",
    },
    {
      key: "name",
      label: "VISIBLE NAME",
      type: "text",
      placeholder: "DeerFlow Research Agent",
      description: "Human-readable display name for operator views.",
    },
    {
      key: "externalAgentId",
      label: "EXTERNAL AGENT ID",
      type: "text",
      placeholder: "research-agent-01",
      description: "Remote-side identifier, if the external framework exposes one.",
    },
    {
      key: "protocolType",
      label: "PROTOCOL",
      type: "select",
      required: true,
      defaultValue: "a2a",
      options: [
        { value: "a2a", label: "A2A" },
        { value: "http", label: "HTTP TASK API" },
        { value: "openclaw_native", label: "OPENCLAW NATIVE" },
        { value: "manual", label: "MANUAL" },
      ],
      description: "How the platform talks to this external agent runtime.",
    },
    {
      key: "baseUrl",
      label: "BASE URL",
      type: "text",
      placeholder: "http://127.0.0.1:3000",
      description: "Required for A2A or HTTP joins. Leave blank for manual / native specs.",
    },
    {
      key: "adapterKind",
      label: "ADAPTER",
      type: "select",
      required: true,
      defaultValue: "a2a_proxy",
      options: [
        { value: "a2a_proxy", label: "A2A PROXY" },
        { value: "http_proxy", label: "HTTP PROXY" },
        { value: "workspace_bridge", label: "WORKSPACE BRIDGE" },
        { value: "manual", label: "MANUAL" },
      ],
      description: "Platform-side adapter family used to bridge this external runtime.",
    },
    {
      key: "sendPath",
      label: "SEND PATH",
      type: "text",
      placeholder: "/a2a/tasks/send or /tasks",
      description: "Optional override for the remote task submission path.",
    },
    {
      key: "taskPathTemplate",
      label: "TASK PATH TEMPLATE",
      type: "text",
      placeholder: "/a2a/tasks/{taskId}",
      description: "Optional override for remote status lookup path template.",
    },
    {
      key: "description",
      label: "DESCRIPTION",
      type: "textarea",
      placeholder: "How this external agent is expected to collaborate with the platform",
      description: "Operator-facing summary for this join spec.",
    },
  ],
  "agent_joins.update": [
    {
      key: "id",
      label: "JOIN ID",
      type: "text",
      required: true,
      aliases: ["joinId"],
      placeholder: "external-lab-main",
      description: "Existing agent join id to update.",
    },
    {
      key: "localAgentId",
      label: "LOCAL ALIAS",
      type: "text",
      placeholder: "blank=keep current",
      description: "Optional new platform-facing alias.",
    },
    {
      key: "platformRole",
      label: "PLATFORM ROLE",
      type: "select",
      optionsSource: "roles",
      description: "Optional new role mapping inside the platform.",
    },
    {
      key: "name",
      label: "VISIBLE NAME",
      type: "text",
      placeholder: "blank=keep current",
      description: "Optional new display name.",
    },
    {
      key: "externalAgentId",
      label: "EXTERNAL AGENT ID",
      type: "text",
      placeholder: "blank=keep current",
      description: "Optional new remote-side identifier.",
    },
    {
      key: "protocolType",
      label: "PROTOCOL",
      type: "select",
      options: [
        { value: "a2a", label: "A2A" },
        { value: "http", label: "HTTP TASK API" },
        { value: "openclaw_native", label: "OPENCLAW NATIVE" },
        { value: "manual", label: "MANUAL" },
      ],
      description: "Optional new protocol family.",
    },
    {
      key: "baseUrl",
      label: "BASE URL",
      type: "text",
      placeholder: "blank=keep current",
      description: "Optional new remote base URL.",
    },
    {
      key: "adapterKind",
      label: "ADAPTER",
      type: "select",
      options: [
        { value: "a2a_proxy", label: "A2A PROXY" },
        { value: "http_proxy", label: "HTTP PROXY" },
        { value: "workspace_bridge", label: "WORKSPACE BRIDGE" },
        { value: "manual", label: "MANUAL" },
      ],
      description: "Optional new platform adapter kind.",
    },
    {
      key: "sendPath",
      label: "SEND PATH",
      type: "text",
      placeholder: "blank=keep current",
      description: "Optional new task submission path.",
    },
    {
      key: "taskPathTemplate",
      label: "TASK PATH TEMPLATE",
      type: "text",
      placeholder: "blank=keep current",
      description: "Optional new remote status path template.",
    },
    {
      key: "description",
      label: "DESCRIPTION",
      type: "textarea",
      placeholder: "blank=keep current",
      description: "Optional new operator-facing summary.",
    },
  ],
  "agent_joins.enable": [
    {
      key: "joinId",
      label: "JOIN ID",
      type: "text",
      required: true,
      description: "Existing agent join id to enable.",
    },
  ],
  "agent_joins.disable": [
    {
      key: "joinId",
      label: "JOIN ID",
      type: "text",
      required: true,
      description: "Existing agent join id to disable.",
    },
  ],
  "agent_joins.delete": [
    {
      key: "joinId",
      label: "JOIN ID",
      type: "text",
      required: true,
      description: "Existing agent join id to delete.",
    },
  ],
});
