// Input-field definitions for automations.*, graph.*, and test.* admin surfaces.

export const AUTOMATION_GRAPH_INPUT_FIELDS = Object.freeze({
  "automations.run": [
    {
      key: "automationId",
      label: "AUTOMATION",
      type: "text",
      required: true,
      placeholder: "nightly-digest",
      description: "Target automation id to run immediately.",
    },
    {
      key: "trigger",
      label: "TRIGGER",
      type: "text",
      placeholder: "manual",
      description: "Optional trigger label recorded into automationContext.",
    },
  ],
  "automations.governance": [
    {
      key: "automationId",
      label: "AUTOMATION",
      type: "text",
      required: true,
      placeholder: "nightly-digest",
      description: "Target automation id whose ProfileLifecycle governance to control.",
    },
    {
      key: "disableGovernanceSnapshot",
      label: "DISABLE SNAPSHOT",
      type: "boolean",
      description: "Circuit breaker: when true, resolveGovernance ignores governanceSnapshot and falls back to spec defaults.",
    },
    {
      key: "reviveProfile",
      label: "REVIVE PROFILE",
      type: "boolean",
      description: "Revive a retired profile: clears governanceSnapshot + profileLifecycle so derived streaks reset.",
    },
  ],
  "graph.edge.add": [
    {
      key: "from",
      label: "FROM",
      type: "select",
      required: true,
      optionsSource: "agents",
      description: "Source agent of the directed collaboration edge.",
    },
    {
      key: "to",
      label: "TO",
      type: "select",
      required: true,
      optionsSource: "agents",
      description: "Target agent of the directed collaboration edge.",
    },
    {
      key: "label",
      label: "LABEL",
      type: "text",
      placeholder: "dispatch / report_back / review",
      description: "Optional visual label shown on the graph edge.",
    },
  ],
  "graph.edge.delete": [
    {
      key: "from",
      label: "FROM",
      type: "select",
      required: true,
      optionsSource: "agents",
      description: "Source agent of the directed collaboration edge to delete.",
    },
    {
      key: "to",
      label: "TO",
      type: "select",
      required: true,
      optionsSource: "agents",
      description: "Target agent of the directed collaboration edge to delete.",
    },
  ],
  "test.inject": [
    {
      key: "message",
      label: "MESSAGE",
      type: "textarea",
      required: true,
      placeholder: "Send a small ingress probe message",
      description: "Injected into the unified ingress path.",
    },
    {
      key: "source",
      label: "SOURCE",
      type: "select",
      options: [
        { value: "webui", label: "WEBUI" },
        { value: "qq", label: "QQ" },
        { value: "a2a", label: "A2A" },
      ],
      defaultValue: "webui",
      description: "Ingress source label used for reply routing and diagnostics.",
    },
    {
      key: "intentType",
      label: "INTENT TYPE",
      type: "select",
      options: [
        { value: "", label: "NONE" },
        { value: "create_task", label: "CREATE_TASK" },
        { value: "assign_task", label: "ASSIGN_TASK" },
        { value: "wake_agent", label: "WAKE_AGENT" },
      ],
      description: "Optional protocol intent hint for standard ingress metadata and diagnostics.",
    },
    {
      key: "phasesText",
      canonicalPath: "phases",
      label: "PHASES",
      type: "textarea",
      valueType: "string_list",
      aliases: ["phases"],
      fallbackPaths: ["intent.params.phases", "params.phases"],
      placeholder: "收集上下文\n执行修改\n整理输出",
      description: "Optional explicit phases for standard ingress. Comma/newline separated.",
    },
  ],
});
