// Input-field definitions for apply.knowledge_* admin surfaces.
// 知识库 ingestion 控制面(Phase 2):operator/UI 经 CLI-system 增删本地知识库条目。
// payload 必须 schema 化,否则 planner 盲猜 kbId/sourcePath,validator 抓不到缺失必填项。
// Handlers: admin-surface-operations.js apply.knowledge_add/reindex/remove。

export const KNOWLEDGE_INPUT_FIELDS = Object.freeze({
  "apply.knowledge_add": [
    {
      key: "kbId",
      label: "KB ID",
      type: "text",
      required: true,
      aliases: ["id", "knowledgeBaseId"],
      placeholder: "my-docs",
      description: "kebab/下划线 ^[a-z0-9_-]+$。库不存在则新建(用户库);'wiki' 为内置保留 id。",
    },
    {
      key: "sourcePath",
      label: "SOURCE PATH",
      type: "text",
      required: true,
      aliases: ["path", "source"],
      placeholder: "docs/ 或 docs/notes.md(相对 ~/.openclaw 或绝对)",
      description: "文件或文件夹路径。文件夹递归;不可读/二进制文件自动跳过。",
    },
    {
      key: "label",
      label: "LABEL",
      type: "text",
      placeholder: "我的文档库",
      description: "可选展示名(默认用 KB ID)。",
    },
  ],
  "apply.knowledge_reindex": [
    {
      key: "kbId",
      label: "KB ID",
      type: "text",
      required: true,
      aliases: ["id", "knowledgeBaseId"],
      placeholder: "my-docs",
      description: "要重建索引的知识库 id('wiki' 重建 wiki 索引)。",
    },
    {
      key: "force",
      label: "FORCE",
      type: "boolean",
      description: "true=全量重嵌(忽略 hash 复用);默认增量。",
    },
  ],
  "apply.knowledge_remove": [
    {
      key: "kbId",
      label: "KB ID",
      type: "text",
      required: true,
      aliases: ["id", "knowledgeBaseId"],
      placeholder: "my-docs",
      description: "要操作的知识库 id(内置 'wiki' 不可删)。",
    },
    {
      key: "sourcePath",
      label: "SOURCE PATH",
      type: "text",
      aliases: ["path", "source"],
      placeholder: "docs/notes.md",
      description: "可选:给了则只删该源(库保留);不给则删整库。",
    },
  ],
  "apply.knowledge_eval_set_save": [
    {
      key: "kbId",
      label: "KB ID",
      type: "text",
      required: true,
      aliases: ["id", "knowledgeBaseId"],
      placeholder: "my-docs",
      description: "评测集绑定的知识库 id。",
    },
    {
      key: "evalSetId",
      label: "EVAL SET ID",
      type: "text",
      required: true,
      placeholder: "baseline",
      description: "评测集 id(同一库可多个)。^[a-z0-9_-]+$。",
    },
    {
      key: "label",
      label: "LABEL",
      type: "text",
      placeholder: "基线召回集",
      description: "可选展示名(默认用 evalSetId)。",
    },
    {
      key: "cases",
      label: "CASES (JSON)",
      type: "textarea",
      required: true,
      placeholder: '[{"query":"如何重启网关","expectedSourcePath":"deploy.md","category":"ops"}]',
      description: "标注数组:每条 {query, expectedSourcePath, category?, expectedKeywords?}。",
    },
  ],
  "apply.knowledge_eval_run": [
    {
      key: "kbId",
      label: "KB ID",
      type: "text",
      required: true,
      aliases: ["id", "knowledgeBaseId"],
      placeholder: "my-docs",
      description: "要评测的知识库 id。",
    },
    {
      key: "evalSetId",
      label: "EVAL SET ID",
      type: "text",
      required: true,
      placeholder: "baseline",
      description: "要跑的评测集 id(须先用 eval_set_save 建好)。",
    },
  ],
  "apply.knowledge_configure": [
    {
      key: "kbId",
      label: "KB ID",
      type: "text",
      required: true,
      aliases: ["id", "knowledgeBaseId"],
      placeholder: "research-reports",
      description: "要配置的知识库 id(内置 wiki 不可配)。",
    },
    {
      key: "temporal",
      label: "TEMPORAL",
      type: "boolean",
      description: "true=时态库(提取 source/time/fields,后续启用时序/分歧);默认 false。",
    },
    {
      key: "metadataRules",
      label: "METADATA RULES (JSON)",
      type: "textarea",
      placeholder: '{"source":{"keys":["issuer","author"],"fallback":"folder"},"time":{"keys":["date","published"],"fallback":"mtime"},"fields":{"passthrough":["target_price","rating"]}}',
      description: "声明 source/time 来自哪些 front-matter 键(fallback: folder|filename|mtime),fields.passthrough 直传哪些键。金融 schema 只活在这里。",
    },
    {
      key: "conflict",
      label: "CONFLICT RULES (JSON)",
      type: "textarea",
      placeholder: '{"groupBy":"fields.ticker","on":["fields.target_price","fields.rating"]}',
      description: "分歧派生:groupBy=同主题分组路径(heading|sourcePath|source|fields.<k>|null),on=要比的标量路径数组。检索时跨源(≥2 发布者)取值有差异即产 conflictHint。",
    },
  ],
  "apply.knowledge_eval_faithfulness": [
    {
      key: "kbId",
      label: "KB ID",
      type: "text",
      required: true,
      aliases: ["id", "knowledgeBaseId"],
      placeholder: "my-docs",
      description: "要跑生成侧评测的知识库 id。",
    },
    {
      key: "evalSetId",
      label: "EVAL SET ID",
      type: "text",
      required: true,
      placeholder: "baseline",
      description: "评测集 id(case 须带 answer 才参与 faithfulness)。",
    },
  ],
  "apply.knowledge_eval_set_remove": [
    {
      key: "kbId",
      label: "KB ID",
      type: "text",
      required: true,
      aliases: ["id", "knowledgeBaseId"],
      placeholder: "my-docs",
      description: "评测集所属知识库 id。",
    },
    {
      key: "evalSetId",
      label: "EVAL SET ID",
      type: "text",
      required: true,
      placeholder: "baseline",
      description: "要删除的评测集 id(幂等)。",
    },
  ],
});
