// Plan hints for agents.* and agent_joins.* admin surfaces.

export const AGENTS_PLAN_HINTS = {
  "agents.create": {
    reads: ["agents.list", "skills.list"],
    writes: ["openclaw.json"],
    generatedFiles: [
      "workspaces/<agent-id>/<role-specific managed guidance files>",
      "workspaces/<agent-id>/agent-card.json",
      "workspaces/<agent-id>/inbox/",
      "workspaces/<agent-id>/outbox/",
      "workspaces/<agent-id>/output/",
    ],
    apiChecks: ["GET /watchdog/agents", "GET /watchdog/skills"],
    expectedSignals: ["alert:agent_created"],
    tests: ["test.inject", "test_runs.start"],
    memos: ["execution-record"],
  },
  "agents.join": {
    reads: ["agents.discovery", "agents.list"],
    writes: [
      "openclaw.json",
      "workspaces/*/agent-card.json",
      "workspaces/*/<role-specific managed guidance files>",
    ],
    generatedFiles: [],
    apiChecks: ["POST /watchdog/agents/join", "GET /watchdog/agents/discovery", "GET /watchdog/agents"],
    expectedSignals: ["alert:agent_enrolled"],
    tests: [],
    memos: ["execution-record"],
  },
  "agents.guidance.takeover": {
    reads: ["agents.discovery", "agents.list"],
    writes: ["workspaces/*/<role-specific managed guidance files>"],
    generatedFiles: [],
    apiChecks: ["POST /watchdog/agents/guidance/takeover", "GET /watchdog/agents/discovery"],
    expectedSignals: ["alert:agent_guidance_taken_over"],
    tests: [],
    memos: ["execution-record"],
  },
  "agents.defaults.model": {
    reads: ["agents.defaults.read", "models.list"],
    writes: ["openclaw.json"],
    generatedFiles: [],
    apiChecks: ["GET /watchdog/agents/defaults"],
    expectedSignals: ["alert:default_model_changed"],
    tests: [],
    memos: ["execution-record"],
  },
  "agents.defaults.heartbeat": {
    reads: ["agents.defaults.read"],
    writes: ["openclaw.json"],
    generatedFiles: [],
    apiChecks: ["GET /watchdog/agents/defaults"],
    expectedSignals: ["alert:default_heartbeat_changed"],
    tests: [],
    memos: ["execution-record"],
  },
  "agents.defaults.skills": {
    reads: ["agents.defaults.read", "skills.list"],
    writes: ["control-plane/agent-default-skills.json", "openclaw.json"],
    generatedFiles: ["control-plane/agent-default-skills.json"],
    apiChecks: ["GET /watchdog/agents/defaults", "GET /watchdog/skills"],
    expectedSignals: ["alert:default_skills_changed"],
    tests: [],
    memos: ["execution-record"],
  },
  "agents.model": {
    reads: ["agents.list", "models.list"],
    writes: ["openclaw.json"],
    generatedFiles: [],
    apiChecks: ["GET /watchdog/agents", "GET /watchdog/models"],
    expectedSignals: ["alert:model_changed"],
    tests: ["test.inject"],
    memos: ["execution-record"],
  },
  "agents.heartbeat": {
    reads: ["agents.list", "agents.defaults.read"],
    writes: ["openclaw.json"],
    generatedFiles: [],
    apiChecks: ["GET /watchdog/agents"],
    expectedSignals: ["alert:agent_heartbeat_changed"],
    tests: [],
    memos: ["execution-record"],
  },
  "agents.policy": {
    reads: ["agents.list"],
    writes: [
      "openclaw.json",
      "workspaces/*/BUILDING-MAP.md",
      "workspaces/*/COLLABORATION-GRAPH.md",
      "workspaces/*/DELIVERY.md",
      "workspaces/*/PLATFORM-GUIDE.md",
    ],
    generatedFiles: [],
    apiChecks: ["GET /watchdog/agents"],
    expectedSignals: ["alert:agent_policies_changed"],
    tests: [],
    memos: ["execution-record"],
  },
  "agents.constraints": {
    reads: ["agents.list"],
    writes: ["workspaces/*/agent-card.json"],
    generatedFiles: [],
    apiChecks: ["GET /watchdog/agents"],
    expectedSignals: ["alert:agent_constraints_changed"],
    tests: [],
    memos: ["execution-record"],
  },
  "agents.name": {
    reads: ["agents.list"],
    writes: ["workspaces/*/agent-card.json"],
    generatedFiles: [],
    apiChecks: ["GET /watchdog/agents"],
    expectedSignals: ["alert:agent_name_changed"],
    tests: [],
    memos: ["execution-record"],
  },
  "agents.description": {
    reads: ["agents.list"],
    writes: ["workspaces/*/agent-card.json"],
    generatedFiles: [],
    apiChecks: ["GET /watchdog/agents"],
    expectedSignals: ["alert:agent_description_changed"],
    tests: [],
    memos: ["execution-record"],
  },
  "agent_joins.list": {
    reads: ["control-plane/agent-join-registry.json"],
    apiChecks: ["GET /watchdog/agent-joins/registry"],
    expectedSignals: [],
  },
  "agent_joins.create": {
    reads: ["agent_joins.list"],
    writes: ["control-plane/agent-join-registry.json"],
    generatedFiles: ["control-plane/agent-join-registry.json"],
    apiChecks: ["POST /watchdog/agent-joins/create", "GET /watchdog/agent-joins/registry"],
    expectedSignals: ["alert:agent_join_updated"],
    tests: [],
    memos: ["execution-record"],
  },
  "agent_joins.update": {
    reads: ["agent_joins.list"],
    writes: ["control-plane/agent-join-registry.json"],
    generatedFiles: [],
    apiChecks: ["POST /watchdog/agent-joins/update", "GET /watchdog/agent-joins/registry"],
    expectedSignals: ["alert:agent_join_updated"],
    tests: [],
    memos: ["execution-record"],
  },
  "agent_joins.enable": {
    reads: ["agent_joins.list"],
    writes: ["control-plane/agent-join-registry.json"],
    generatedFiles: [],
    apiChecks: ["POST /watchdog/agent-joins/enable", "GET /watchdog/agent-joins/registry"],
    expectedSignals: ["alert:agent_join_updated"],
    tests: [],
    memos: ["execution-record"],
  },
  "agent_joins.disable": {
    reads: ["agent_joins.list"],
    writes: ["control-plane/agent-join-registry.json"],
    generatedFiles: [],
    apiChecks: ["POST /watchdog/agent-joins/disable", "GET /watchdog/agent-joins/registry"],
    expectedSignals: ["alert:agent_join_updated"],
    tests: [],
    memos: ["execution-record"],
  },
  "agent_joins.delete": {
    reads: ["agent_joins.list"],
    writes: ["control-plane/agent-join-registry.json"],
    generatedFiles: [],
    apiChecks: ["POST /watchdog/agent-joins/delete", "GET /watchdog/agent-joins/registry"],
    expectedSignals: ["alert:agent_join_updated"],
    tests: [],
    memos: ["execution-record"],
  },
  "agents.tools": {
    reads: ["agents.list"],
    writes: ["openclaw.json", "workspaces/*/agent-card.json"],
    generatedFiles: [],
    apiChecks: ["GET /watchdog/agents"],
    expectedSignals: ["alert:agent_tools_changed"],
    tests: [],
    memos: ["execution-record"],
  },
  "agents.card.formats": {
    reads: ["agents.list"],
    writes: ["workspaces/*/agent-card.json"],
    generatedFiles: [],
    apiChecks: ["GET /watchdog/agents"],
    expectedSignals: ["alert:agent_card_formats_changed"],
    tests: [],
    memos: ["execution-record"],
  },
  "agents.role": {
    reads: ["agents.list"],
    writes: ["workspaces/*/agent-card.json", "openclaw.json"],
    generatedFiles: [
      "workspaces/<agent-id>/AGENTS.md",
      "workspaces/<agent-id>/BUILDING-MAP.md",
      "workspaces/<agent-id>/COLLABORATION-GRAPH.md",
      "workspaces/<agent-id>/DELIVERY.md",
      "workspaces/<agent-id>/PLATFORM-GUIDE.md",
    ],
    apiChecks: ["GET /watchdog/agents"],
    expectedSignals: ["alert:agent_role_changed"],
    tests: [],
    memos: ["execution-record"],
  },
  "agents.skills": {
    reads: ["agents.list", "skills.list"],
    writes: ["openclaw.json", "workspaces/*/agent-card.json"],
    generatedFiles: [
      "workspaces/<agent-id>/AGENTS.md",
      "workspaces/<agent-id>/BUILDING-MAP.md",
      "workspaces/<agent-id>/COLLABORATION-GRAPH.md",
      "workspaces/<agent-id>/DELIVERY.md",
      "workspaces/<agent-id>/PLATFORM-GUIDE.md",
    ],
    apiChecks: ["GET /watchdog/agents", "GET /watchdog/skills"],
    expectedSignals: ["alert:agent_skills_changed"],
    tests: [],
    memos: ["execution-record"],
  },
  "agents.delete": {
    reads: ["agents.list"],
    writes: ["openclaw.json"],
    generatedFiles: [],
    apiChecks: ["GET /watchdog/agents"],
    expectedSignals: ["alert:agent_deleted"],
    tests: ["test.inject"],
    memos: ["execution-record"],
  },
  "agents.hard_delete": {
    reads: ["agents.list", "agents.discovery"],
    writes: ["openclaw.json", "workspaces/<resolved-target>/**"],
    generatedFiles: [],
    apiChecks: ["GET /watchdog/agents", "GET /watchdog/agents/discovery", "POST /watchdog/agents/hard-delete"],
    expectedSignals: ["alert:agent_hard_deleted"],
    tests: ["test.inject"],
    memos: ["execution-record"],
  },
};
