// Plan hints for admin_change_sets.*, automations.*, graph.*, runtime.loop.*,
// test_runs.start, test.inject, and runtime.reset admin surfaces.

export const APPLY_REST_PLAN_HINTS = {
  "admin_change_sets.save": {
    reads: ["admin_surfaces.list"],
    writes: ["control-plane/admin-change-sets/*.json"],
    generatedFiles: ["control-plane/admin-change-sets/ACS-<timestamp>-<hex>.json"],
    apiChecks: [
      "POST /watchdog/admin-change-sets",
      "GET /watchdog/admin-change-sets",
      "GET /watchdog/admin-change-sets/detail?id=<draft-id>",
    ],
    expectedSignals: [],
    tests: [],
    memos: ["execution-record"],
  },
  "admin_change_sets.attach_verification": {
    reads: [
      "admin_change_sets.detail",
      "test_runs.detail",
      "test-reports/*.json",
    ],
    writes: ["control-plane/admin-change-sets/*.json"],
    generatedFiles: [],
    apiChecks: [
      "POST /watchdog/admin-change-sets/verification",
      "GET /watchdog/admin-change-sets/detail?id=<draft-id>",
      "GET /watchdog/test-runs/detail?id=<run-id>",
    ],
    expectedSignals: [],
    tests: [],
    memos: ["execution-record"],
  },
  "admin_change_sets.execute": {
    reads: ["admin_change_sets.detail", "admin_change_sets.preview"],
    writes: ["control-plane/admin-change-sets/*.json"],
    generatedFiles: [],
    apiChecks: [
      "POST /watchdog/admin-change-sets/execute",
      "GET /watchdog/admin-change-sets/detail?id=<draft-id>",
    ],
    expectedSignals: [],
    tests: [],
    memos: ["execution-record"],
  },
  "automations.run": {
    reads: ["automations.list", "work_items.list"],
    writes: [
      "control-plane/automation-runtime.json",
      "control-plane/contracts/*.json",
      "research-lab/loop_session_state.json",
    ],
    generatedFiles: [],
    apiChecks: [
      "POST /watchdog/automations/run",
      "GET /watchdog/automations",
    ],
    expectedSignals: ["alert:automation_round_started"],
    tests: [],
    memos: ["execution-record"],
  },
  "graph.edge.add": {
    reads: ["agents.list", "control-plane/agent-graph.json"],
    writes: [
      "control-plane/agent-graph.json",
      "workspaces/*/BUILDING-MAP.md",
      "workspaces/*/COLLABORATION-GRAPH.md",
      "workspaces/*/PLATFORM-GUIDE.md",
    ],
    generatedFiles: [],
    apiChecks: ["GET /watchdog/graph"],
    expectedSignals: ["alert:graph_updated"],
    tests: [],
    memos: ["execution-record"],
  },
  "graph.edge.delete": {
    reads: ["agents.list", "control-plane/agent-graph.json"],
    writes: [
      "control-plane/agent-graph.json",
      "workspaces/*/BUILDING-MAP.md",
      "workspaces/*/COLLABORATION-GRAPH.md",
      "workspaces/*/PLATFORM-GUIDE.md",
    ],
    generatedFiles: [],
    apiChecks: ["GET /watchdog/graph"],
    expectedSignals: ["alert:graph_updated"],
    tests: [],
    memos: ["execution-record"],
  },
  "graph.loop.compose": {
    reads: ["agents.list", "control-plane/agent-graph.json"],
    writes: [
      "control-plane/agent-graph.json",
      "workspaces/*/BUILDING-MAP.md",
      "workspaces/*/COLLABORATION-GRAPH.md",
      "workspaces/*/PLATFORM-GUIDE.md",
    ],
    generatedFiles: [],
    apiChecks: ["GET /watchdog/graph", "GET /watchdog/graph/loops"],
    expectedSignals: ["alert:graph_updated"],
    tests: [],
    memos: ["execution-record"],
  },
  "graph.loop.repair": {
    reads: ["control-plane/graph-loop-registry.json", "control-plane/agent-graph.json", "research-lab/loop_session_state.json"],
    writes: [
      "control-plane/agent-graph.json",
      "workspaces/*/BUILDING-MAP.md",
      "workspaces/*/COLLABORATION-GRAPH.md",
      "workspaces/*/PLATFORM-GUIDE.md",
    ],
    generatedFiles: [],
    apiChecks: ["GET /watchdog/graph", "GET /watchdog/graph/loops", "GET /watchdog/graph/loop-sessions"],
    expectedSignals: ["alert:graph_updated"],
    tests: [],
    memos: ["execution-record", "architecture-memo-if-behavior-changed"],
  },
  "runtime.loop.start": {
    reads: ["control-plane/graph-loop-registry.json", "research-lab/loop_session_state.json"],
    writes: ["research-lab/loop_session_state.json", "workspaces/*/inbox/contract.json"],
    generatedFiles: [],
    apiChecks: ["GET /watchdog/graph", "GET /watchdog/graph/loop-sessions"],
    expectedSignals: ["alert:loop_started"],
    tests: [],
    memos: ["execution-record", "architecture-memo-if-behavior-changed"],
  },
  "runtime.loop.interrupt": {
    reads: ["research-lab/loop_session_state.json"],
    writes: ["research-lab/loop_session_state.json"],
    generatedFiles: [],
    apiChecks: ["GET /watchdog/graph", "GET /watchdog/graph/loop-sessions"],
    expectedSignals: ["alert:loop_interrupted"],
    tests: [],
    memos: ["execution-record", "architecture-memo-if-behavior-changed"],
  },
  "runtime.loop.resume": {
    reads: ["research-lab/loop_session_state.json", "control-plane/graph-loop-registry.json"],
    writes: ["research-lab/loop_session_state.json", "workspaces/*/inbox/contract.json"],
    generatedFiles: [],
    apiChecks: ["GET /watchdog/graph", "GET /watchdog/graph/loop-sessions"],
    expectedSignals: ["alert:loop_resumed"],
    tests: [],
    memos: ["execution-record", "architecture-memo-if-behavior-changed"],
  },
  "test_runs.start": {
    reads: ["test_runs.list", "work_items.list"],
    writes: [
      "runtime reset state",
      "watchdog test run store",
      "control-plane/contracts/*.json",
      "workspaces/*/mailbox inbox/outbox/**",
      "test-reports/*",
    ],
    generatedFiles: ["test-reports/<report-file>"],
    apiChecks: ["GET /watchdog/test-runs", "GET /watchdog/test-runs/detail?id=<run-id>"],
    expectedSignals: ["alert:test_delivery_recorded", "alert:test_sink_notified", "alert:qq_notify"],
    tests: ["self"],
    memos: [],
  },
  "test.inject": {
    reads: ["agents.list", "work_items.list"],
    writes: ["control-plane/contracts/*.json", "control-plane/output/*.md"],
    generatedFiles: ["control-plane/contracts/TC-<timestamp>.json"],
    apiChecks: ["GET /watchdog/work-items", "GET /watchdog/runtime"],
    expectedSignals: ["alert:inbox_dispatch"],
    tests: ["self"],
    memos: [],
  },
  "runtime.reset": {
    reads: ["runtime.read", "work_items.list", "research-lab/loop_session_state.json"],
    writes: [
      "control-plane/watchdog-state.json",
      "control-plane/queue-state.json",
      "research-lab/loop_session_state.json",
      "control-plane/contracts/*.json",
    ],
    generatedFiles: [],
    apiChecks: ["GET /watchdog/runtime", "GET /watchdog/graph/loop-sessions"],
    expectedSignals: ["alert:system_reset"],
    tests: [],
    memos: ["execution-record"],
  },
};
